apiVersion: v2
name: monitoring
description: A Helm chart for Kubernetes monitoring stack (Prometheus, Grafana, Loki, Alertmanager)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - monitoring
  - prometheus
  - grafana
  - loki
  - alertmanager
home: https://github.com/sre-desafio/monitoring
sources:
  - https://github.com/sre-desafio/monitoring
maintainers:
  - name: SRE Team
    email: sre@example.com 