# Default values for monitoring chart
# This is a YAML-formatted file.

# Namespace configuration
namespace:
  create: true
  name: monitoring

# Prometheus configuration
prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: "v2.45.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9090
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  storage:
    size: 10Gi

# Grafana configuration
grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: "10.0.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  adminPassword: "admin123"
  persistence:
    enabled: true
    size: 5Gi

# Loki configuration
loki:
  enabled: true
  image:
    repository: grafana/loki
    tag: "2.9.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3100
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  storage:
    size: 10Gi

# Promtail configuration
promtail:
  enabled: true
  image:
    repository: grafana/promtail
    tag: "2.8.4"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Alertmanager configuration
alertmanager:
  enabled: true
  image:
    repository: prom/alertmanager
    tag: "v0.26.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9093
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  storage:
    size: 1Gi

# Global configuration
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
  annotations: {}
  labels: {} 